#!/usr/bin/env python3
"""Generate or check THIRD-PARTY-NOTICES.md from `cargo metadata` (task 1.3)."""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "THIRD-PARTY-NOTICES.md"
ALLOWED = {"MIT", "Apache-2.0", "BSD-3-Clause", "Unicode-3.0", "Zlib", "BSD-2-Clause", "0BSD", "MPL-2.0", "ISC", "CC0-1.0", "Unlicense", "Unicode-DFS-2016"}


def resolved_packages():
    meta = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1", "--all-features"], cwd=ROOT))
    workspace = set(meta["workspace_members"])
    by_id = {p["id"]: p for p in meta["packages"]}
    ids = [n["id"] for n in meta["resolve"]["nodes"]]
    pkgs = []
    for pid in sorted(set(ids)):
        if pid in workspace:
            continue
        p = by_id[pid]
        pkgs.append((p["name"], p["version"], p.get("license") or "UNKNOWN", p.get("repository") or ""))
    pkgs.sort()
    return pkgs


def license_ok(expr: str) -> bool:
    tokens = [t.strip() for t in expr.replace("(", " ").replace(")", " ").replace("/", " OR ").split() if t.strip() not in {"OR", "AND", "WITH"}]
    # SQLite's bundled C is public domain; rusqlite/libsqlite3-sys license expressions cover it.
    return any(t in ALLOWED for t in tokens) and not any(t.startswith("GPL") for t in tokens)


def render(pkgs):
    lines = ["# Third-Party Notices", "", "Generated by `scripts/gen-licenses.py`. Rust dependencies resolved for all features; the Swift package has no third-party dependencies. SQLite (bundled by `libsqlite3-sys`) is public domain.", "", "| Crate | Version | License | Repository |", "|---|---|---|---|"]
    for name, version, lic, repo in pkgs:
        lines.append(f"| {name} | {version} | {lic} | {repo} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    pkgs = resolved_packages()
    bad = [(n, v, l) for n, v, l, _ in pkgs if not license_ok(l)]
    if bad:
        print("licenses outside the allow-list:", bad)
        return 1
    text = render(pkgs)
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print("THIRD-PARTY-NOTICES.md is out of date; run scripts/gen-licenses.py")
            return 1
        print(f"THIRD-PARTY-NOTICES.md up to date ({len(pkgs)} dependencies)")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(pkgs)} dependencies)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
